### Create a new candidacy (id = 1)
POST http://localhost:8080/candidacy
Content-Type: application/json

{
  "studentId": 2,
  "offer": {
    "id": 1
  }
}

### Get candidacies by student (id = 2)
GET http://localhost:8080/candidacy/student
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkLmRAZ21sLmNvbSIsImlhdCI6MTcyOTA5NjQ2OCwiZXhwIjoxNzMwMzkyNDY4fQ.75bgh6HUAe9occBlfYKJalr4fo-5lkrwD8bBgEbiwGM
Content-Type: application/json

