### Register a new recruiter (id = 1)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "role": "RECRUITER",
  "firstname": "Jane",
  "lastname": "Smith",
  "email": "jane.sth@eple.com",
  "password": "password",
  "companyId": 1,
  "birthDate": "1985-08-15"
}

### Register a new student (id = 2)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "role": "STUDENT",
  "firstname": "darko",
  "lastname": "dj",
  "email": "d.d@gml.com",
  "password": "securepassword",
  "schoolName": "SU",
  "skillIds" : [9, 10],
  "gradeId" : 5,
  "fieldId" : 36,
  "birthDate": "1985-08-15"
}

### Register a new student (id = 2)
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "recruiter@example.com",
  "password": "password"
}


### Register a new student (id = 2)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "role": "STUDENT",
  "firstname": "Yanis",
  "lastname": "tabellout",
  "email": "yanis@gmail.com",
  "password": "yanis",
  "schoolName": "SU",
  "skillIds" : [9, 10],
  "gradeId" : 5,
  "fieldId" : 36,
  "birthDate": "1985-08-15"
}

### Register a new recruiter (id = 3)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "role": "RECRUITER",
  "firstname": "Yanis",
  "lastname": "Tabellout",
  "email": "yanisr@gmail.com",
  "password": "yanis",
  "companyId": 1,
  "birthDate": "1985-08-15"
}


### Register a new student (id = 2)
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "yanis@gmail.com",
  "password": "yanis"
}
### Register a new student (id = 2)
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "yanisr@gmail.com",
  "password": "yanis"
}
