version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  #back:
  #  build: .
  #  restart: on-failure
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - db

volumes:
  postgres_data:
  postgres_backup:
