version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    #networks:
    #  network:
    #    ipv4_address: 172.20.0.2
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    #networks:
    #  network:
    #    ipv4_address: 172.20.0.3
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # Port pour les connexions AMQP
      - "15672:15672" # Port pour l'interface de gestion
    environment:
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_DEFAULT_USER: myuser
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    #networks:
    #  network:
    #    ipv4_address: 172.20.0.4
  security:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    #networks:
    #  network:
    #    ipv4_address: 172.20.0.5

volumes:
  rabbitmq_data:
  rabbitmq_log:

#networks:
#  network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16